export const GET_SHOPITEMS = "GET_SHOPITEMS";
export const EDIT_SHOPITEM_SUCCESS = "EDIT_SHOPITEM_SUCCESS";
export const EDIT_SHOPITEM_ERROR = "EDIT_SHOPITEM_ERROR";
export const CREATE_SHOPITEM_SUCCESS = "CREATE_SHOPITEM_SUCCESS";
export const CREATE_SHOPITEM_ERROR = "CREATE_SHOPITEM_ERROR";
export const DELETE_SHOPITEM_SUCCESS = "DELETE_SHOPITEM_SUCCESS";
export const DELETE_SHOPITEM_ERROR = "DELETE_SHOPITEM_ERROR";