export const GET_SHOPS = "GET_SHOPS";
export const EDIT_SHOP_SUCCESS = "EDIT_SHOP_SUCCESS";
export const EDIT_SHOP_ERROR = "EDIT_SHOP_ERROR";
export const CREATE_SHOP_SUCCESS = "CREATE_SHOP_SUCCESS";
export const CREATE_SHOP_ERROR = "CREATE_SHOP_ERROR";
export const DELETE_SHOP_SUCCESS = "DELETE_SHOP_SUCCESS";
export const DELETE_SHOP_ERROR = "DELETE_SHOP_ERROR";